using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TsumegoSystem : MonoBehaviour
{
<<<<<<< HEAD
    public TsumegoInfo CurTsumegoInfo { get; set; }
=======
    public TsumegoInfo CurTsumegoInfo;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.C))
        {
            CheckClear();
        }
    }
>>>>>>> parent of 8b20a26 (0321 ыЈИьЇ ь  ьЛЄыА)

    public void CheckClear()
    {
        foreach(var condition in CurTsumegoInfo.Conditions)
        {
            if (!condition.CheckCondition())
            {
<<<<<<< HEAD
=======
                // НЧЦа
>>>>>>> parent of 8b20a26 (0321 ыЈИьЇ ь  ьЛЄыА)
                Debug.Log("НЧЦа");
                return;
            }
        }
<<<<<<< HEAD
=======

        // СЖАЧ РќКЮ ХыАњЧд
>>>>>>> parent of 8b20a26 (0321 ыЈИьЇ ь  ьЛЄыА)
        ClearStage();
    }

    public void ClearStage()
    {
        // SOПЁ ХЌИЎОю УГИЎ
        CurTsumegoInfo.IsClear = true;
        Debug.Log("МКАј");

        // ХЌИЎОю ПЌУт, КИЛѓ СіБо, ХЌИЎОю ЕЅРЬХЭ АЛНХ УГИЎ
    }
}
